"use strict ";
const axios = require("axios");
//const apikey = "86659dd4361cc4c9af8c572a494ac06f"; // your api key to the api generated by the website

const getGhibli = location => {
    return new Promise(async (resolve, reject) => {
        try {
            const movieInformation = await axios.get(
                "https://ghibliapi.herokuapp.com/films",
                //"http://api.openweathermap.org/data/2.5/forecast?id=524901&appid=86659dd4361cc4c9af8c572a494ac06f",
                //"http://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}",
                // write your api address access here , for instance : " http://api.apixu.com/v1/forecast.json " ,
                );

            resolve(movieInformation.data) // returns back the results to the chatbot
        }
        catch (error) {
            reject(error);
        }
    });
}

module.exports = getGhibli;