"use strict ";
const axios = require("axios");
const apikey = "86659dd4361cc4c9af8c572a494ac06f"; // your api key to the api generated by the website

const getWeather = location => {
    return new Promise(async (resolve, reject) => {
        try {
            const weatherConditions = await axios.get(
                "http://api.openweathermap.org/data/2.5/forecast?id=524901&appid=86659dd4361cc4c9af8c572a494ac06f",
                //"http://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}",
                // write your api address access here , for instance : " http://api.apixu.com/v1/forecast.json " ,
                {
                    params: {
                        key: apikey,
                        q: location,
                        days: 3
                    }
                });

            resolve(weatherConditions.data) // returns back the results to the chatbot
        }
        catch (error) {
            reject(error);
        }
    });
}

module.exports = getWeather;